image:
#- Visual Studio 2017
 - Ubuntu

clone_depth: 3

before_build:
- sh: sudo apt-get -yq update > /dev/null
- sh: sudo apt-get install -yq --no-install-suggests --no-install-recommends gnudatalanguage > /dev/null
  
after_build:
- gdl -e @test2
- gdl -e @test1

