image:
#- Visual Studio 2017
- Ubuntu

clone_depth: 3

build: off

init:
- mkdir ~/astrolib

- sh: wget https://idlastro.gsfc.nasa.gov/ftp/astron.dir.tar.gz
- sh: tar -xf astron.dir.tar.gz -C ~/astrolib

- sh: sudo apt-get -yq update > /dev/null
- sh: sudo apt-get install -yq --no-install-suggests --no-install-recommends gnudatalanguage > /dev/null

test_script:
- gdl -e @test2
- gdl -e @test1

