language: python
group: travis_latest

git:
  depth: 3
  quiet: true

os:
  - linux

addons:
  apt:
    packages:
      - gnudatalanguage

install:
  - mkdir ~/astrolib
  - wget https://idlastro.gsfc.nasa.gov/ftp/astron.dir.tar.gz
  - tar -xf astron.dir.tar.gz -C ~/astrolib

script:
  - gdl -e @test



