language: minimal
group: travis_latest

git:
  depth: 25
  quiet: true

#addons:
#  apt:
#    packages:
#      - gnudatalanguage

before_install:
- sudo apt-get -yq update > /dev/null
- sudo apt-get install -yq --no-install-suggests --no-install-recommends gnudatalanguage > /dev/null
  
install:
- mkdir ~/astrolib
- wget https://idlastro.gsfc.nasa.gov/ftp/astron.dir.tar.gz
- tar -xf astron.dir.tar.gz -C ~/astrolib

script:
- gdl -e @test2
- gdl -e @test1

